Repository pgcentralfoundation/pgrx, pull requests merged in 2021-09, with the labels that each got.

#172 Added support for uuid PostgreSQL type
  README.md
  pgx-tests/sql/load-order.txt
  pgx-tests/src/tests/mod.rs
  pgx-tests/src/tests/uuid_tests.rs
  pgx/src/datum/mod.rs
  pgx/src/datum/uuid.rs
Labels: enhancement

#185 fix: attempt repair docsrs build
  Cargo.toml
  pgx-macros/Cargo.toml
  pgx-pg-sys/Cargo.toml
  pgx/Cargo.toml
Labels: bug, documentation

#223 fix: mark called_as_trigger as unsafe
  pgx/src/trigger_support.rs
Labels: bug

#224 fix: Mark PgTupleDesk::from_pg_copy unsafe
  pgx/src/tupdesc.rs
Labels: bug

#226 fix: Mark get_getarg_type unsafe
  pgx/src/fcinfo.rs
Labels: bug
