Repository pgcentralfoundation/pgrx, pull requests merged in 2022-12, with the labels that each got.

#922 Ensuring owned memory context is not current when dropping it (extension)
  pgx-tests/src/tests/memcxt_tests.rs
  pgx/src/memcxt.rs
Labels: 0.6.1

#959 Fix typos
  articles/forging-sql-from-rust.md
  articles/postgresql-aggregates-with-rust.md
  cargo-pgx/README.md
  cargo-pgx/src/command/schema.rs
  pgx-examples/composite_type/src/lib.rs
  pgx-examples/operators/README.md
  pgx-macros/src/lib.rs
  pgx-pg-config/src/lib.rs
  pgx-pg-config/src/path_methods.rs
  pgx-pg-sys/build.rs
  pgx-pg-sys/src/submodules/thread_check.rs
  pgx-sql-entity-graph/src/mapping.rs
  pgx-sql-entity-graph/src/pg_extern/mod.rs
  pgx-sql-entity-graph/src/pg_extern/returning.rs
  pgx-sql-entity-graph/src/pgx_attribute.rs
  pgx-tests/src/framework.rs
  pgx-tests/src/tests/json_tests.rs
  pgx-version-updater/src/main.rs
  pgx/src/datum/array.rs
  pgx/src/datum/internal.rs
  pgx/src/datum/numeric.rs
  pgx/src/datum/varlena.rs
  pgx/src/fcinfo.rs
  pgx/src/heap_tuple.rs
  pgx/src/itemptr.rs
  pgx/src/lib.rs
  pgx/src/pgbox.rs
  pgx/src/trigger_support/pg_trigger.rs
Labels: needs-rebase

#962 clone implementation for PgTupleDesc
  pgx-tests/src/tests/heap_tuple.rs
  pgx/src/tupdesc.rs
Labels: enhancement, perf, merge-conflicts
