Repository pgcentralfoundation/pgrx, pull requests merged in 2022-11, with the labels that each got.

#831 Remove `pgx::datum::Array::over`
  pgx-tests/src/tests/array_tests.rs
  pgx/src/datum/array.rs
Labels: breaks-API

#842 Allow installing cargo-pgx using rustls instead of native-tls
  cargo-pgx/Cargo.toml
Labels: cargo pgx

#840 Warns about unsupported PG versions during bindgen
  pgx-pg-sys/build.rs
Labels: ffi-bindgen

#777 Detect and complain about use of `pgx-pg-sys` functions from multiple threads
  Cargo.lock
  pgx-pg-sys/Cargo.toml
  pgx-pg-sys/src/submodules/mod.rs
  pgx-pg-sys/src/submodules/setjmp.rs
  pgx-pg-sys/src/submodules/thread_check.rs
Labels: ffi-safety

#841 Updates update-versions.sh script to use pgx-version-updater
  Cargo.lock
  pgx-version-updater/Cargo.toml
  pgx-version-updater/src/main.rs
  update-versions.sh
Labels: releases

#886 Make `PgRelation::with_lock` unsafe
  pgx/src/rel.rs
Labels: breaks-API

#864 Make time-crate an optional dep
  pgx-tests/src/tests/datetime_tests.rs
  pgx/Cargo.toml
  pgx/src/datum/date.rs
  pgx/src/datum/time.rs
  pgx/src/datum/time_stamp.rs
  pgx/src/datum/time_stamp_with_timezone.rs
  pgx/src/datum/time_with_timezone.rs
Labels: breaks-API

#894 Seal PgNode
  pgx-pg-sys/build.rs
  pgx-pg-sys/src/lib.rs
Labels: breaks-API
