Repository pgcentralfoundation/pgrx, pull requests merged in 2022-10, with the labels that each got.

#733 Stop binding system headers and a few other things
  Cargo.lock
  pgx-pg-sys/Cargo.toml
  pgx-pg-sys/build.rs
  pgx/src/memcxt.rs
Labels: ffi-bindgen

#736 Pass `-isysroot` to bindgen on macOS
  Cargo.lock
  pgx-pg-config/src/lib.rs
  pgx-pg-sys/Cargo.toml
  pgx-pg-sys/build.rs
Labels: ffi-bindgen

#709 Enable low-level access to the database catalog
  pgx-pg-sys/include/pg10.h
  pgx-pg-sys/include/pg11.h
  pgx-pg-sys/include/pg12.h
  pgx-pg-sys/include/pg13.h
  pgx-pg-sys/include/pg14.h
Labels: ffi-bindgen

#784 SRF functions need to "fetch" (call `FromDatum`) each argument while …
  pgx-examples/strings/src/lib.rs
  pgx-tests/src/tests/srf_tests.rs
  pgx-utils/src/lib.rs
  pgx-utils/src/sql_entity_graph/pg_extern/mod.rs
Labels: bug

#820 Update clap and related dependencies
  Cargo.lock
  cargo-pgx/Cargo.toml
  cargo-pgx/src/command/connect.rs
  cargo-pgx/src/command/get.rs
  cargo-pgx/src/command/init.rs
  cargo-pgx/src/command/install.rs
  cargo-pgx/src/command/new.rs
  cargo-pgx/src/command/package.rs
  cargo-pgx/src/command/pgx.rs
  cargo-pgx/src/command/run.rs
  cargo-pgx/src/command/schema.rs
  cargo-pgx/src/command/start.rs
  cargo-pgx/src/command/status.rs
  cargo-pgx/src/command/stop.rs
  cargo-pgx/src/command/test.rs
  cargo-pgx/src/main.rs
  cargo-pgx/src/metadata.rs
Labels: deps

#822 Multiple Linux distros nightly run -- re-publishing content from #796
  .dockerignore
  .github/docker/Dockerfile.alpine:3.16
  .github/docker/Dockerfile.amazon:2
  .github/docker/Dockerfile.debian:bullseye
  .github/docker/Dockerfile.fedora:36
  .github/docker/run-docker.sh
  .github/workflows/will-it-blend-develop.yml
  pgx-pg-sys/src/lib.rs
Labels: ci

#780 Initial stab at a design doc
  DESIGN-DECISIONS.md
Labels: docs
