Repository pgcentralfoundation/pgrx, pull requests merged in 2022-09, with the labels that each got.

#662 Add `RawArray::nulls_bitslice` with bitvec
  Cargo.lock
  pgx-tests/src/tests/array_tests.rs
  pgx/Cargo.toml
  pgx/src/array.rs
  pgx/src/datum/array.rs
Labels: before-next:0.5

#643 Opaque Timestamp/Tz types
  pgx-tests/src/tests/datetime_tests.rs
  pgx/src/datum/time_stamp.rs
  pgx/src/datum/time_stamp_with_timezone.rs
Labels: breaks-API, deprecation, before-next:0.5

#666 Rewrite Spi{Ok,Error} without num-traits
  Cargo.lock
  pgx/Cargo.toml
  pgx/src/lib.rs
  pgx/src/spi.rs
Labels: deps, before-next:0.5

#665 Increases verbosity of pgx-tests in various places
  cargo-pgx/src/command/install.rs
  pgx-pg-config/src/lib.rs
  pgx-tests/src/framework.rs
Labels: test-support

#672 Deprecate `Array<'a, T>::as_slice`
  pgx-examples/arrays/src/lib.rs
  pgx-pg-sys/src/submodules/mod.rs
  pgx-pg-sys/src/submodules/polyfill.rs
  pgx-tests/src/tests/array_tests.rs
  pgx-tests/src/tests/heap_tuple.rs
  pgx/src/array.rs
  pgx/src/datum/array.rs
  pgx/src/layout.rs
  pgx/src/lib.rs
Labels: deprecation, before-next:0.5

#646 Input functions should take Option
  pgx-macros/src/lib.rs
  pgx-tests/src/tests/fcinfo_tests.rs
  pgx/src/datum/mod.rs
  pgx/src/inoutfuncs.rs
Labels: before-next:0.5

#677 Match the Postgres repr in Time and TimeWithTimeZone
  pgx-tests/src/tests/datetime_tests.rs
  pgx/src/datum/time.rs
  pgx/src/datum/time_stamp.rs
  pgx/src/datum/time_stamp_with_timezone.rs
  pgx/src/datum/time_with_timezone.rs
Labels: ffi-safety, breaks-API, deprecation, before-next:0.5

#685 Remove unused code
  pgx-macros/src/lib.rs
  pgx-utils/src/lib.rs
  pgx-utils/src/rewriter.rs
Labels: after-next:0.5.0
