Repository pgcentralfoundation/pgrx, pull requests merged in 2023-12, with the labels that each got.

#1418 :fix: avoid segfault on background worker pool exhaustion
  pgrx-tests/src/tests/bgworker_tests.rs
  pgrx/src/bgworkers.rs
Labels: breaks-API

#1426 Deprecate `Oid::from_u32_unchecked` in 0.11.2
  pgrx-pg-sys/src/submodules/oids.rs
Labels: deprecation

#1423 Tighten up `Pg_magic_func` code
  pgrx-examples/custom_types/src/lib.rs
  pgrx/src/lib.rs
Labels: breaks-API

#1342 Add `MemCx<'mcx>` for `List<'mcx, T>`
  docs/src/pg-internal/memory-context.md
  pgrx-tests/src/tests/list_tests.rs
  pgrx/src/fn_call.rs
  pgrx/src/lib.rs
  pgrx/src/list.rs
  pgrx/src/list/flat_list.rs
  pgrx/src/list/linked_list.rs
  pgrx/src/memcx.rs
  pgrx/src/pg_catalog/pg_proc.rs
  pgrx/src/pg_sys.rs
Labels: breaks-API

#1432 feat: add `ForeignDataWrapperRelationId` OID definitions
  pgrx-pg-sys/include/pg12.h
  pgrx-pg-sys/include/pg13.h
  pgrx-pg-sys/include/pg14.h
  pgrx-pg-sys/include/pg15.h
  pgrx-pg-sys/include/pg16.h
Labels: ffi-bindgen

#1431 Include rule utils header
  pgrx-pg-sys/include/pg12.h
  pgrx-pg-sys/include/pg13.h
  pgrx-pg-sys/include/pg14.h
  pgrx-pg-sys/include/pg15.h
  pgrx-pg-sys/include/pg16.h
Labels: ffi-bindgen

#1440 fix issue #1437
  pgrx-sql-entity-graph/src/postgres_enum/mod.rs
  pgrx-tests/src/tests/enum_type_tests.rs
Labels: bug
